### ISSUE TITLE
[dev] 前端登录环节和论坛内相关服务整合

### ISSUE THREAD

**Issue by Rebornix-zero** [Cealgull/cealgull.app#16]
### Dev Focus

feat 🚄

### Dev Priority

High 🔋

### Dev Scope

前端界面完善

### Description

准备于周二进行一次前端两部分的对接，以完成前端应用主体功能

### Goals

1. 登陆部分完成后，希望能向论坛部分发送用户的 wallet, 或者获取用户 wallet 的信息，由于登陆后跳转至 PerosnView 界面，故传递的方式为向 PerosnView 对应的 Navigation Screen 传递 wallet（或其他）字段即可，只要发送过来，后续的处理我这边就可以做到了
2. 帖子的回复需要展开一个文本+图片编辑器，希望能够复用发布页的相关组件来做，如果做好对应的组件，明天就可以整合，从而完成应用主体功能

**Comment by rennsax** [comment]
Solved by #19
